language: something
install:
- echo "Installed"
script:
  - sh .travis/publish.sh
after_success:
  - sh .travis/deploy.sh
env:
  global:
  - DITAMAP=DITA/en/pbx/api-v2.ditamap
  - DITAVAL=DITA/ditaval/s-series.ditaval
  - ANT_OPTS=-Xmx1024M
  
before_install:
- openssl aes-256-cbc -K $encrypted_ed75db31fc5b_key -iv $encrypted_ed75db31fc5b_iv -in licenseKey.txt.enc -out licenseKey.txt -d


